name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8  
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/
      
      - name: Build Docker Image
        uses: FlowSquad/docker-cloud-build@v1.0.1
        with:
          gcp-project-id: bipolarfactoryfastapi
          gcp-service-account-key: ${{ secrets.GCP_SA_KEY }}
          image-name: hello-world
          image-sources: Dockerfile
          github-disabled: true
          github-token: ${{ secrets.GIT }}